version: '3'
services:
  redis:
    restart: always
    image: redislabs/redisearch
    ports:
      - '6379:6379'
  web:
    restart: always
    build: ./
    depends_on:
      - redis
    ports:
      - '8000:8000'
